# Generated by Django 5.2.2 on 2025-09-05 11:26

from django.db import migrations, models
from django.contrib.auth.models import User
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField()),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
