# Generated by Django 5.2.6 on 2025-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user_alter_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('others', 'Others')], default='EQUIPMENT', max_length=50),
        ),
    ]
