# Generated by Django 5.2.6 on 2025-10-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_product_seller_alter_product_id'),
    ]

    operations = [
    ]
