# Generated by Django 5.2.6 on 2025-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20251007_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('others', 'Others')], default='EQUIPMENT', max_length=50),
        ),
    ]
