# Generated by Django 5.2.2 on 2025-10-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category'),
    ]

    operations = [
        # First, ensure the necessary PostgreSQL extension is enabled
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'),

        # Next, run the SQL to alter the column correctly
        migrations.RunSQL(
            sql="""
            ALTER TABLE main_product
            ALTER COLUMN id SET DEFAULT uuid_generate_v4(),
            ALTER COLUMN id TYPE UUID USING (uuid_generate_v4());
            """,
            # SQL to reverse the change (good practice)
            reverse_sql="""
            ALTER TABLE main_product
            ALTER COLUMN id TYPE BIGINT USING (0);
            """
        ),
    ]
